# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-16 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170912_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topicclass',
            name='topic',
        ),
        migrations.AddField(
            model_name='topicclass',
            name='topic_id',
            field=models.IntegerField(db_index=True, default=1, unique=True),
            preserve_default=False,
        ),
    ]
